version: "3.9"

services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: test2
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
        ports:
            - 5432:5432
    redis:
        image: redis
        command: redis-server
        ports:
            - 6379:6379