# Generated by Django 3.2.9 on 2021-12-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_examresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.visit'),
        ),
    ]
