# Generated by Django 3.2.9 on 2022-01-13 19:09

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('core', '0007_visit_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('priority', models.IntegerField()),
                ('assigned_ambulance', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ambulance')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('hospitaluser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.hospitaluser')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.hospitaluser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('drivers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.driver')),
            ],
        ),
        migrations.RenameModel(
            old_name='Patient',
            new_name='Dispositor',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='ExamResult',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
        migrations.AddField(
            model_name='ambulancecall',
            name='assigned_squad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.squad'),
        ),
        migrations.AddField(
            model_name='ambulancecall',
            name='caller_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location'),
        ),
    ]
