# Generated by Django 3.2.9 on 2022-01-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220113_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='vehicle_name',
            field=models.CharField(default='Renault Master', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='registration_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
