# Generated by Django 3.2.9 on 2022-01-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220116_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ambulancecall',
            name='caller_location',
        ),
        migrations.AddField(
            model_name='ambulance',
            name='city',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambulance',
            name='number',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambulance',
            name='street',
            field=models.CharField(default='l', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambulancecall',
            name='city',
            field=models.CharField(default='l', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambulancecall',
            name='number',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambulancecall',
            name='street',
            field=models.CharField(default='dad', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
