# Generated by Django 3.2.9 on 2022-01-22 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220116_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='drivers',
        ),
        migrations.AddField(
            model_name='driver',
            name='squad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.squad'),
        ),
    ]
