# Generated by Django 3.2.9 on 2022-01-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220122_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='squad',
        ),
        migrations.AddField(
            model_name='squad',
            name='drivers',
            field=models.ManyToManyField(to='core.Driver'),
        ),
    ]
